# Generated by Django 5.2.4 on 2025-08-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ticker',
        ),
        migrations.AddField(
            model_name='transaction',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.holding'),
            preserve_default=False,
        ),
    ]
