# Generated by Django 5.2.4 on 2025-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_transaction_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
